name: dayan_dev_container
services:
  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    restart: always
  postgres:
    container_name: postgres_container
    image: imresamu/postgis-arm64 #postgis/postgis
    platform: linux/arm64/v8
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always